// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Counts { lemmas: number, konseps: number, golongan_katas: number, cakupans: number, kata_asings: number, }