// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CakupanData } from "./CakupanData";
import type { GolonganKataData } from "./GolonganKataData";
import type { KataAsingData } from "./KataAsingData";

export interface KonsepData { id: number, golongan_kata: GolonganKataData, keterangan: string | null, tertib: number | null, cakupan: Array<CakupanData> | null, kata_asing: Array<KataAsingData> | null, }