// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KataAsingItem } from "./KataAsingItem";

export interface KonsepItem { id: number, keterangan: string, golongan_kata: string, cakupans: Array<string>, kata_asing: Array<KataAsingItem>, }