// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KonsepItem } from "./KonsepItem";

export interface LemmaItem { id: number, lemma: string, konseps: Array<KonsepItem>, }