// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KonsepData } from "./KonsepData";

export interface LemmaData { id: number, nama: string, konseps: Array<KonsepData> | null, }