// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Filter { lemma: string | null, konsep: string | null, cakupan: Array<string> | null, kata_asing: Array<string> | null, }