// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface KataAsing { id: number, tarikh_masuk: number, nama: string, bahasa: string, }