// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Konsep { id: number, tarikh_masuk: number, lemma_id: number, golongan_id: string | null, keterangan: string | null, tertib: number | null, }