// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CakupanData } from "./CakupanData";
import type { KataAsingData } from "./KataAsingData";

export interface KonsepData { id: number | null, tarikh_masuk: number | null, lemma_id: number | null, golongan_id: string | null, keterangan: string | null, tertib: number | null, cakupans: Array<CakupanData> | null, kata_asings: Array<KataAsingData> | null, }