// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KonsepData } from "./KonsepData";
import type { LemmaData } from "./LemmaData";

export interface SamudraData { lemma: LemmaData, konseps: Array<KonsepData>, }