//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "golongan_kata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub tarikh_masuk: DateTimeUtc,
    pub nama: String,
    pub keterangan: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::konsep::Entity")]
    Konsep,
}

impl Related<super::konsep::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Konsep.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
