//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "kata_asing")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tarikh_masuk: DateTimeUtc,
    pub nama: String,
    pub bahasa: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::konsep::Entity> for Entity {
    fn to() -> RelationDef {
        super::kata_asing_x_konsep::Relation::Konsep.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::kata_asing_x_konsep::Relation::KataAsing.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
