//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod cakupan;
pub mod cakupan_x_konsep;
pub mod golongan_kata;
pub mod kata_asing;
pub mod kata_asing_x_konsep;
pub mod konsep;
pub mod lemma;
