//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::cakupan::Entity as Cakupan;
pub use super::cakupan_x_konsep::Entity as CakupanXKonsep;
pub use super::golongan_kata::Entity as GolonganKata;
pub use super::kata_asing::Entity as KataAsing;
pub use super::kata_asing_x_konsep::Entity as KataAsingXKonsep;
pub use super::konsep::Entity as Konsep;
pub use super::lemma::Entity as Lemma;
